### ISSUE TITLE
missing break;

### ISSUE THREAD

**Issue by zutzm** [MorrisJobke/strengthify#11]
in jquery.strengthify.js
line 110
 case 3:
                        css = 'password-good';
                        bsLevel = 'info';
                        message = "Getting better.";

missing closing break;

**Comment by MorrisJobke** [comment]
@zutzm Could I ask you to open this change as a pull request? That would be awesome 😃 See https://help.github.com/articles/using-pull-requests/ how to do this.

You could also do all of this directly in your browser: https://help.github.com/articles/editing-files-in-your-repository/

**Comment by MorrisJobke** [comment]
Fixed in #13
