### ISSUE TITLE
eval() call prevents script-src CSP

### ISSUE THREAD

**Issue by JakeSteam** [MorrisJobke/strengthify#19]
[CSP](https://www.html5rocks.com/en/tutorials/security/content-security-policy/) is an extremely useful setting for securing websites. Currently strengthify cannot coexist with secure script configurations, as it uses `eval()` in `strengthify.js` on approximately line 200.

A quick fix is replacing:

                $.ajax({
                    cache: true,
                    url: options.zxcvbn
                }).done(function(content) {
                    eval(content);
                    $elem.bind('keyup input change', drawSelf);
                });

with:

                $elem.parent().on('scroll', drawSelf);
                $.getScript(options.zxcvbn);
                $elem.bind('keyup input change', drawSelf);

I'm unsure of any negative side effects of this, but I haven't noticed any, and CSP is now happy!

**Comment by oschwald** [comment]
We also ran into this issue when evaluating strengthify.

**Comment by rullzer** [comment]
@MorrisJobke could you have a look at this?

**Comment by MorrisJobke** [comment]
Released as 0.5.4 https://github.com/MorrisJobke/strengthify/releases/tag/0.5.4
