### ISSUE TITLE
version number in source is wrong

### ISSUE THREAD

**Issue by bmaster001** [MorrisJobke/strengthify#22]
The version number in the jquery.strengthify.js file (line 5) is 0.5.2... that should be 0.5.3.  Took a while to find out why my code wasn't executing the onResult function, while my version of the source matched the version on github :-)

**Comment by MorrisJobke** [comment]
Thanks for the hint. I updated it but did not updated the package. I hope this is still fine.

**Comment by bmaster001** [comment]
Sure, it's no big issue :-)  Thanks!
